/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_forms;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.JFrame;

/**
 *
 * @author Dusty
 */
public class AboutUS4 extends javax.swing.JFrame {

    /**
     * Creates new form AboutUS
     */
    public AboutUS4() {
        initComponents();
               this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }
    
public static void openWebPage(String url) {
        try {
            Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
            if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
                desktop.browse(new URI(url));
            }
            throw new NullPointerException();
        } catch (Exception e) {
          //  JOptionPane.showMessageDialog(null, url, "", JOptionPane.PLAIN_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_twiter = new javax.swing.JButton();
        btn_insg = new javax.swing.JButton();
        btn_facebook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/A reader .png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 340, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/11-1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 370, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/11.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 380, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/10.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 380, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/9.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 380, 40));

        btn_twiter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/twitter.png"))); // NOI18N
        btn_twiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_twiterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_twiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 50, 40));

        btn_insg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/instagram-logo.png"))); // NOI18N
        btn_insg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insgActionPerformed(evt);
            }
        });
        getContentPane().add(btn_insg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 50, 40));

        btn_facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/if_Facebook_194929.png"))); // NOI18N
        btn_facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facebookActionPerformed(evt);
            }
        });
        getContentPane().add(btn_facebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("@wiselibrary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("wiselibrary@mail.com");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("info desk 82-475-97");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Black BC.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1030, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_facebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facebookActionPerformed
        // TODO add your handling code here:
        openWebPage("https://www.facebook.com");
    }//GEN-LAST:event_btn_facebookActionPerformed

    private void btn_twiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_twiterActionPerformed
        // TODO add your handling code here:
        openWebPage("https://twitter.com/");
    }//GEN-LAST:event_btn_twiterActionPerformed

    private void btn_insgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insgActionPerformed
        // TODO add your handling code here:
        openWebPage("https://www.instagram.com");
    }//GEN-LAST:event_btn_insgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutUS4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutUS4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutUS4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutUS4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutUS4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_facebook;
    private javax.swing.JButton btn_insg;
    private javax.swing.JButton btn_twiter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
