/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_forms;

import Controller.basicFunctions;
import Data.LoadedData;
import Listener.Message;
import Listener.communicationManager;
import Models.Bill;
import Models.Book;
import Models.CartList;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dusty
 */
public class Bill5 extends javax.swing.JFrame implements communicationManager{
    private basicFunctions mcontroller;
    private String gender_text= "male";
    private ArrayList<Book> myBooks = new ArrayList<>();

    /**
     * Creates new form Bill
     */
    public Bill5() {
        initComponents();
         mcontroller = new basicFunctions();
        mcontroller.setListenerCommunication(this);
               this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

               
              
        
         male.setActionCommand("male");
         female.setActionCommand("female");
       
         male.getModel().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                gender_text = e.getActionCommand();
            }
        });
          female.getModel().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               gender_text = e.getActionCommand();
            }
        });
        gender.add(male);
        gender.add(female);
        gender.setSelected(male.getModel(), true);
        if(LoadedData.getInstance().getCurrentUser() != null){
            mcontroller.SelectMyCartlist(LoadedData.getInstance().getCurrentUser().getId());
        }else{
       JOptionPane.showMessageDialog(this,"You must login to see your items","Compete",JOptionPane.WARNING_MESSAGE);
 
        }
    //  items.setText(gender_text);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        totalprice = new javax.swing.JTextField();
        arrivaldate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        items = new javax.swing.JTextArea();
        totalpriceafterdiscount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        btn_logout = new javax.swing.JButton();
        btn_homepage = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        numberphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        btn_confirm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/user info.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("Male");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("Female");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("Gender");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, 20));
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, 20));
        getContentPane().add(totalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 150, -1));
        getContentPane().add(arrivaldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 150, -1));

        items.setColumns(20);
        items.setRows(5);
        jScrollPane1.setViewportView(items);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 210, -1));
        getContentPane().add(totalpriceafterdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 90, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Arrival Date");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 160, -1));

        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.setToolTipText("logout from account");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        btn_homepage.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_homepage.setText("Back to Home Page");
        btn_homepage.setToolTipText("");
        btn_homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homepageActionPerformed(evt);
            }
        });
        getContentPane().add(btn_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Price After Discount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 140, 20));

        numberphone.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        numberphone.setForeground(new java.awt.Color(204, 204, 204));
        numberphone.setText("Required field");
        getContentPane().add(numberphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Phone number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        lname.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        lname.setForeground(new java.awt.Color(204, 204, 204));
        lname.setText("Required field");
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 150, -1));

        btn_confirm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_confirm.setText("Confirm");
        btn_confirm.setToolTipText("Confirm purchase");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });
        getContentPane().add(btn_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Items");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Total price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        address.setForeground(new java.awt.Color(204, 204, 204));
        address.setText("Required field");
        address.setToolTipText("");
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 150, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        fname.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        fname.setForeground(new java.awt.Color(204, 204, 204));
        fname.setText("Required field");
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Square.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 350, 470));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("First Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/BILL WORD.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 160, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Square.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 350, 470));

        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("THANK YOU FOR VISITING US");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/BC.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homepageActionPerformed
        // TODO add your handling code here:
         new HomePage3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homepageActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        LoadedData.getInstance().setCurrentUser(null);
        new HomePage3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        // TODO add your handling code here:
        String result_fname = fname.getText().toString();
        String result_lname =lname.getText().toString();
        String result_address =address.getText().toString();
        String result_numberphone =numberphone.getText().toString();
        String result_date =date.getText().toString();
        String result_items =items.getText();
        double result_totalprice =Double.parseDouble(totalprice.getText().toString());
        double result_totalpriceafterdiscount =Double.parseDouble(totalpriceafterdiscount.getText().toString());
        String result_arribaldate =arrivaldate.getText();
        if(result_fname.isEmpty() || result_lname.isEmpty()|| result_address.isEmpty()|| result_numberphone.isEmpty()){
                JOptionPane.showMessageDialog(this,"fill all required field","Compete",JOptionPane.INFORMATION_MESSAGE);

            return;
        }
        Bill b = new Bill(result_fname,result_lname,result_numberphone,
                result_address,gender_text,result_date,result_items
        ,result_totalprice,result_totalpriceafterdiscount,result_arribaldate);
        mcontroller.addBill(b);
    }//GEN-LAST:event_btn_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField arrivaldate;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_homepage;
    private javax.swing.JButton btn_logout;
    private javax.swing.JTextField date;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextArea items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField numberphone;
    private javax.swing.JTextField totalprice;
    private javax.swing.JTextField totalpriceafterdiscount;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnCompete(Message msg) {
         // show a joptionpane dialog using showMessageDialog
         double totoalPrice = 0;
                      System.out.println("msg :"+msg);

         if(msg.getStauts() == communicationManager.STATUS_SUCCESSFUL && msg.getContent() != null){
             ArrayList<Book> books = (ArrayList)msg.getContent();
             myBooks = books;
             for(Book b : books){
             items.setText(items.getText()+"\n"+b.getName());
             totoalPrice+=b.getPrice();
             }
             totalprice.setText(""+totoalPrice);
         }else if(msg.getContent() ==null){
                 JOptionPane.showMessageDialog(this,msg.getMessage(),"Compete",JOptionPane.INFORMATION_MESSAGE);

         }
         
    }

    @Override
    public void OnFailure(Message msg) {
          JOptionPane.showMessageDialog(this,msg.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);

    }
}
