/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_forms;

import Data.LoadedData;
import DataBase.DB;
import Models.User;
import javax.swing.JFrame;

/**
 *
 * @author Dhuha
 */
public class HomePage3 extends javax.swing.JFrame {
    private User currentUser;

    /**
     * Creates new form Home
     */
    public HomePage3() {
        // connect to server and create table for first time
        DB.getInstance().createTables();
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        if(LoadedData.getInstance().getCurrentUser() != null){
            currentUser = LoadedData.getInstance().getCurrentUser();
            displayUsername.setText("Welcome (^-^)"+currentUser.getName());
            btn_sigUp.setVisible(false);
            signup_lable.setVisible(false);
           
        }else{
             displayUsername.setVisible(false);
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_overlay = new javax.swing.JPanel();
        displayUsername = new javax.swing.JLabel();
        signup_lable = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textMgazin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_books = new javax.swing.JButton();
        btn_megazin = new javax.swing.JButton();
        btn_aboutus = new javax.swing.JButton();
        btn_sigUp = new javax.swing.JButton();
        billText = new javax.swing.JLabel();
        Bill = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayUsername.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        displayUsername.setForeground(new java.awt.Color(0, 153, 153));
        displayUsername.setText("UserName");
        pnl_overlay.add(displayUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 460, 50));

        signup_lable.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        signup_lable.setForeground(new java.awt.Color(255, 255, 255));
        signup_lable.setText("Click here to sign up");
        pnl_overlay.add(signup_lable, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ABOUT US");
        pnl_overlay.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, -1, -1));

        textMgazin.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        textMgazin.setForeground(new java.awt.Color(255, 255, 255));
        textMgazin.setText("MAGAZINE");
        pnl_overlay.add(textMgazin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Untitled-3.png"))); // NOI18N
        pnl_overlay.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("WISE WHERE YOU CAN READ, BUY AND RENT BOOKS EASLY!");
        pnl_overlay.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 850, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BOOKS");
        pnl_overlay.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        btn_books.setBackground(new java.awt.Color(0, 0, 0));
        btn_books.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        btn_books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_booksActionPerformed(evt);
            }
        });
        pnl_overlay.add(btn_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        btn_megazin.setBackground(new java.awt.Color(0, 0, 0));
        btn_megazin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        btn_megazin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_megazinActionPerformed(evt);
            }
        });
        pnl_overlay.add(btn_megazin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        btn_aboutus.setBackground(new java.awt.Color(0, 0, 0));
        btn_aboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        btn_aboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutusActionPerformed(evt);
            }
        });
        pnl_overlay.add(btn_aboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, -1, -1));

        btn_sigUp.setBackground(new java.awt.Color(0, 0, 0));
        btn_sigUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        btn_sigUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigUpActionPerformed(evt);
            }
        });
        pnl_overlay.add(btn_sigUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        billText.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        billText.setForeground(new java.awt.Color(255, 255, 255));
        billText.setText("Bill");
        pnl_overlay.add(billText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, -1, -1));

        Bill.setBackground(new java.awt.Color(0, 0, 0));
        Bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillActionPerformed(evt);
            }
        });
        pnl_overlay.add(Bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/textura-de-saten-negro.jpg"))); // NOI18N
        pnl_overlay.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1200));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_megazinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_megazinActionPerformed
        // TODO add your handling code here:
          new MagazinUI().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_btn_megazinActionPerformed

    private void btn_booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_booksActionPerformed
        // TODO add your handling code here:
          new BOOK4().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btn_booksActionPerformed

    private void btn_aboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutusActionPerformed
        // TODO add your handling code here:
          new AboutUS4().setVisible(true);
          
    }//GEN-LAST:event_btn_aboutusActionPerformed

    private void btn_sigUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigUpActionPerformed
        // TODO add your handling code here:
        new SignUp2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_sigUpActionPerformed

    private void BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillActionPerformed
        // TODO add your handling code here:
        new Bill5().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Bill;
    private javax.swing.JLabel billText;
    private javax.swing.JButton btn_aboutus;
    private javax.swing.JButton btn_books;
    private javax.swing.JButton btn_megazin;
    private javax.swing.JButton btn_sigUp;
    private javax.swing.JLabel displayUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JLabel signup_lable;
    private javax.swing.JLabel textMgazin;
    // End of variables declaration//GEN-END:variables
}
