/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_forms;

import Controller.basicFunctions;
import Data.LoadedData;
import Listener.Message;
import Listener.communicationManager;
import Models.User;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhuha
 */
public class LogIn2 extends javax.swing.JFrame implements communicationManager{
    private basicFunctions mcontroller;

    /**
     * Creates new form Home
     */
    public LogIn2() {
        initComponents();
         mcontroller = new basicFunctions();
        mcontroller.setListenerCommunication(this);
               this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_overlay = new javax.swing.JPanel();
        GOText = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        usernameText = new javax.swing.JLabel();
        usernameText1 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        UserNAme = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        z5rfa = new javax.swing.JLabel();
        coloredPanel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GOText.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        GOText.setForeground(new java.awt.Color(255, 255, 255));
        GOText.setText("GO");
        pnl_overlay.add(GOText, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, -1, -1));

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/GO CIRCLE.png"))); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_overlay.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 100, 100));
        pnl_overlay.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 260, 50));

        username.setBackground(new java.awt.Color(208, 208, 208));
        pnl_overlay.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 309, 260, 50));

        usernameText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setText("Password: ");
        pnl_overlay.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, -1));

        usernameText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        usernameText1.setForeground(new java.awt.Color(255, 255, 255));
        usernameText1.setText("User Name:");
        pnl_overlay.add(usernameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        Password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        pnl_overlay.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        UserNAme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        pnl_overlay.add(UserNAme, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, -1));

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/login.png"))); // NOI18N
        pnl_overlay.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 440, -1));

        z5rfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/ADDS.png"))); // NOI18N
        pnl_overlay.add(z5rfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 440, -1));

        coloredPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/COLORED BC.png"))); // NOI18N
        pnl_overlay.add(coloredPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 370, 660));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/BCC.png"))); // NOI18N
        pnl_overlay.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 660));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 829));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String usr = username.getText().toString();
        String pass = password.getText().toString();
        mcontroller.loginUserUnlessAddress(usr, pass);
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel GOText;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel UserNAme;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel coloredPanel;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameText;
    private javax.swing.JLabel usernameText1;
    private javax.swing.JLabel z5rfa;
    // End of variables declaration//GEN-END:variables

     @Override
    public void OnCompete(Message msg) {
         // show a joptionpane dialog using showMessa geDialog
        
         if(msg.getStauts() == communicationManager.STATUS_NOT_FOUND){
                    JOptionPane.showMessageDialog(this,msg.getMessage(),"Compete",JOptionPane.WARNING_MESSAGE);
  
         }else{
         User currentUser =(User) msg.getContent();
         LoadedData.getInstance().setCurrentUser(currentUser);
         JOptionPane.showMessageDialog(this,msg.getMessage(),"Compete",JOptionPane.INFORMATION_MESSAGE);
         new HomePage3().setVisible(true);
         this.dispose();
         }
    }

    @Override
    public void OnFailure(Message msg) {
          JOptionPane.showMessageDialog(this,msg.getMessage(),"Failure",JOptionPane.ERROR_MESSAGE);

    }
}
