/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_forms;

import Controller.basicFunctions;
import Data.LoadedData;
import Listener.Message;
import Listener.communicationManager;
import Models.CartList;
import Models.Magazin;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nadakhalid
 */
public class Search1 extends javax.swing.JFrame implements communicationManager {

    private basicFunctions mcontroller;
    private DefaultListModel model;
    private Magazin selectedMagazin;
    public static JFrame SearchScreen;
    private boolean isAddedToCartList = false;


    /**
     * Creates new form AuthorBooks
     */
    public Search1() {
        initComponents();
        mcontroller = new basicFunctions();
        mcontroller.setListenerCommunication(this);
        SearchScreen = this;
                MagazinUI.GetInstance().setListenerSearchForm(this);

       this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        if(MagazinUI.GetInstance() == null ){
      JOptionPane.showMessageDialog(this, "You can not Enter directly go to magazine or books page and click search", "Failure", JOptionPane.ERROR_MESSAGE);
       this.dispose();
       System.exit(0);
        }
        this.setPreferredSize(new Dimension(200, 400));
         model = new DefaultListModel<Magazin>();
          btn_home.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                new HomePage3().setVisible(true);
                SearchScreen.dispose();
            }
            
            @Override
            public void mousePressed(MouseEvent e) {
            }
            
            @Override
            public void mouseReleased(MouseEvent e) {
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        
        btn_logout.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                LoadedData.getInstance().setCurrentUser(null);
                new HomePage3().setVisible(true);
                SearchScreen.dispose();
            }
            
            @Override
            public void mousePressed(MouseEvent e) {
            }
            
            @Override
            public void mouseReleased(MouseEvent e) {
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
            }
            
            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_home = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        result_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addToCart = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        result_description = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        result_author = new javax.swing.JTextField();
        result_genre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Athelas", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Res.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 60, 340, 60);

        jLabel5.setFont(new java.awt.Font("Athelas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 140, 90, 24);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Home.png"))); // NOI18N
        getContentPane().add(btn_home);
        btn_home.setBounds(360, 510, 0, 0);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/logout.png"))); // NOI18N
        getContentPane().add(btn_logout);
        btn_logout.setBounds(470, 520, 0, 0);
        getContentPane().add(result_name);
        result_name.setBounds(400, 160, 100, 20);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setText("Search again");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 430, 90, 20);

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Res.png"))); // NOI18N
        btn_search.setText("jButton2");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search);
        btn_search.setBounds(330, 430, 110, 20);

        jLabel3.setFont(new java.awt.Font("Athelas", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Result");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 70, 220, 40);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Add to cart");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 430, 90, 20);

        addToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Res.png"))); // NOI18N
        addToCart.setText("jButton2");
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });
        getContentPane().add(addToCart);
        addToCart.setBounds(470, 430, 110, 20);

        jLabel8.setFont(new java.awt.Font("Athelas", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 190, 110, 24);
        getContentPane().add(result_description);
        result_description.setBounds(400, 210, 100, 30);

        jLabel13.setFont(new java.awt.Font("Athelas", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("author");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(400, 240, 90, 24);
        getContentPane().add(result_author);
        result_author.setBounds(400, 260, 100, 30);
        getContentPane().add(result_genre);
        result_genre.setBounds(400, 320, 100, 40);

        jLabel14.setFont(new java.awt.Font("Athelas", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("genre");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(400, 300, 90, 24);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/res2.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 120, 400, 400);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/BC.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        SearchScreen.setVisible(false);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        if(LoadedData.getInstance().getCurrentUser() != null){
        CartList mitem = new CartList(LoadedData.getInstance().getCurrentUser().getId(),selectedMagazin.getId(),"magazin");
        mcontroller.addItemInCardList(mitem);
        }else{
   JOptionPane.showMessageDialog(this,"You must login to add this item", "Failure", JOptionPane.WARNING_MESSAGE);
   
        }
    }//GEN-LAST:event_addToCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart;
    private javax.swing.JLabel btn_home;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField result_author;
    private javax.swing.JTextField result_description;
    private javax.swing.JTextField result_genre;
    private javax.swing.JTextField result_name;
    // End of variables declaration//GEN-END:variables

    @Override
    public void OnCompete(Message msg) {
        int status = msg.getStauts();
        Object Content = msg.getContent();
        // i come form BOOK4
       
        if(Content!=null && !(Content instanceof ArrayList)){
            Magazin b = (Magazin)Content;
            selectedMagazin = b;
          result_name.setText(b.getName());
           result_description.setText(b.getDescription());
            result_author.setText(b.getPublishing());
             result_genre.setText(b.getGenre());
        }else{
          JOptionPane.showMessageDialog(this,"There are no books founded","Compete",JOptionPane.INFORMATION_MESSAGE);
        
        }
        if(status == STATUS_SUCCESSFUL && isAddedToCartList){
      JOptionPane.showMessageDialog(this,msg.getMessage(),"Compete",JOptionPane.INFORMATION_MESSAGE);
      isAddedToCartList = false;

        }
//        // show a joptionpane dialog using showMessageDialog
//        //   JOptionPane.showMessageDialog(this,msg.getMessage(),"Compete",JOptionPane.INFORMATION_MESSAGE);
//        if ( msg.getContent() != null) {
//            if (msg.getContent() instanceof ArrayList) {
//                ArrayList<Book> books = (ArrayList) msg.getContent();
//                for (Book bk : books) {
//                    model.addElement(bk);
//                }
//            }
//           
//        }
//        else if(msg.getStauts() == communicationManager.STATUS_SUCCESSFUL && msg.getContent() != null){
//             JOptionPane.showMessageDialog(this, msg.getMessage(), "successfully", JOptionPane.INFORMATION_MESSAGE);
//           
//            }else if (msg.getStauts() == communicationManager.STATUS_SUCCESSFUL){
//                         JOptionPane.showMessageDialog(this, "successfully added", "successfully", JOptionPane.INFORMATION_MESSAGE);
//
//        }

    }

    @Override
    public void OnFailure(Message msg) {
        JOptionPane.showMessageDialog(this, msg.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

    }
}
