/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_forms;

import Controller.basicFunctions;
import Data.LoadedData;
import Listener.Message;
import Listener.communicationManager;
import Models.Book;
import Models.User;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dhuha
 */
public class SignUp2 extends javax.swing.JFrame implements communicationManager {

    private basicFunctions mcontroller;
    private User newUser;

    /**
     * Creates new form Home
     */
    public SignUp2() {
        initComponents();
        mcontroller = new basicFunctions();
        mcontroller.setListenerCommunication(this);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    private void WriteInFile(String content) {
        BufferedWriter bw = null;
        FileWriter fw = null;
        try {
            
            File file = new File("/users.txt");
            if (!file.exists()) {
file.createNewFile();
}
            fw = new FileWriter(file);
            bw = new BufferedWriter(fw);
            bw.write(content);

        } catch (IOException ex) {
                   JOptionPane.showMessageDialog(this,"can not wirte to file :"+ex.getLocalizedMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

        } finally {
            if (bw != null) {
                try {
                    bw.close();
                } catch (IOException ex) {
                   JOptionPane.showMessageDialog(this,"can not wirte to file :"+ ex.getLocalizedMessage(), "Failure", JOptionPane.ERROR_MESSAGE);
                }
            }

            if (fw != null) {
                try {
                    fw.close();
                } catch (IOException ex) {
                   JOptionPane.showMessageDialog(this,"can not wirte to file :"+ ex.getLocalizedMessage(), "Failure", JOptionPane.ERROR_MESSAGE);
                }
            }

        }

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_overlay = new javax.swing.JPanel();
        already = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        usernameText3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        usernameText2 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JLabel();
        fieldName = new javax.swing.JLabel();
        z5rfa = new javax.swing.JLabel();
        usernameText1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        usernameText = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        GOText = new javax.swing.JLabel();
        btn_regeister = new javax.swing.JButton();
        coloredPanel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_overlay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        already.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        already.setForeground(new java.awt.Color(153, 153, 153));
        already.setText("Already have an account? ");
        pnl_overlay.add(already, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, -1, -1));

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/Sign up.png"))); // NOI18N
        pnl_overlay.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 440, -1));

        usernameText3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        usernameText3.setForeground(new java.awt.Color(255, 255, 255));
        usernameText3.setText("Email: ");
        pnl_overlay.add(usernameText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, -1, -1));
        pnl_overlay.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 270, 50));

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 102, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_overlay.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, -1, -1));

        usernameText2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        usernameText2.setForeground(new java.awt.Color(255, 255, 255));
        usernameText2.setText("User Name:");
        pnl_overlay.add(usernameText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        fieldEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        pnl_overlay.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        fieldName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/username.png"))); // NOI18N
        pnl_overlay.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        z5rfa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/ADDS.png"))); // NOI18N
        pnl_overlay.add(z5rfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 440, -1));

        usernameText1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        usernameText1.setForeground(new java.awt.Color(255, 255, 255));
        usernameText1.setText("User Name:");
        pnl_overlay.add(usernameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, -1, -1));

        name.setBackground(new java.awt.Color(208, 208, 208));
        pnl_overlay.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 260, 50));

        usernameText.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setText("Password: ");
        pnl_overlay.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, -1, -1));

        email.setBackground(new java.awt.Color(208, 208, 208));
        pnl_overlay.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, 260, 50));

        GOText.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        GOText.setForeground(new java.awt.Color(255, 255, 255));
        GOText.setText("GO");
        pnl_overlay.add(GOText, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, -1, -1));

        btn_regeister.setBackground(new java.awt.Color(0, 0, 0));
        btn_regeister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/GO CIRCLE.png"))); // NOI18N
        btn_regeister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regeisterActionPerformed(evt);
            }
        });
        pnl_overlay.add(btn_regeister, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 100, 100));

        coloredPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/COLORED BC.png"))); // NOI18N
        pnl_overlay.add(coloredPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 370, 660));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/publicImage/BCC.png"))); // NOI18N
        pnl_overlay.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 660));

        getContentPane().add(pnl_overlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 829));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        new LogIn2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_regeisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regeisterActionPerformed
        // TODO add your handling code here:
        String usrName = name.getText().toString();
        String usrpassword = password.getText().toString();
        String usremail = email.getText().toString();
        newUser = new User(usrName, usremail, usrpassword);
        WriteInFile("name==>"+usrName+"    email=>"+usremail+"    password=>"+usrpassword);
        mcontroller.regeisterUserUnlessAddress(newUser);
    }//GEN-LAST:event_btn_regeisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp2.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel GOText;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel already;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_regeister;
    private javax.swing.JLabel coloredPanel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fieldEmail;
    private javax.swing.JLabel fieldName;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel pnl_overlay;
    private javax.swing.JLabel usernameText;
    private javax.swing.JLabel usernameText1;
    private javax.swing.JLabel usernameText2;
    private javax.swing.JLabel usernameText3;
    private javax.swing.JLabel z5rfa;
    // End of variables declaration//GEN-END:variables
 @Override
    public void OnCompete(Message msg) {
        // show a joptionpane dialog using showMessageDialog
        if (msg.getContent() != null) {
            int id = (int) msg.getContent();
            newUser.setId(id);
            LoadedData.getInstance().setCurrentUser(newUser);
            JOptionPane.showMessageDialog(this, msg.getMessage(), "Compete", JOptionPane.INFORMATION_MESSAGE);
            new HomePage3().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Something happend " + msg.getMessage(), "Compete", JOptionPane.WARNING_MESSAGE);

        }
    }

    @Override
    public void OnFailure(Message msg) {
        JOptionPane.showMessageDialog(this, msg.getMessage(), "Failure", JOptionPane.ERROR_MESSAGE);

    }
}
